package src;

public enum CAEX {
    JOVEM_EMPREENDEDOR_INOVADOR,
    PROPRIEDADE_INTELECTUAL_ALFENAS,
    APRIMORAMENTO_JR_DESENVOLVENDO_EMPRESAS_JUNIORES,
    UNIFAL_MAIS_EMPREENDEDORA,
    NIDUSLAB_MAKER_MAO_NA_MASSA,
    ROBOTICA_EDUCACIONAL_INOVACAO_COLABORATIVA,
    TRANSFORMANDO_PESQUISAS_EM_PRODUTOS_MERCADOLOGICOS,
    EMPREENDENDO_E_PROTEGENDO_SUAS_IDEIAS;
}
